autoSectionPath = "src"
changelog = true
gitSourceBranch = "main"
title = "JanitorUtilities"

[docusaurus]
tagline = "Utilities for Janitor to expand its functionality"

[[navbar.items]]
href = "https://discord.gg/nhDpg96Srt"
label = "Discord"
position = "right"

[[navbar.items]]
href = "https://twitter.com/howmanysmaII"
label = "Twitter"
position = "right"

[home]
enabled = true
includeReadme = false

[[home.features]]
description = "Expanded functionality? Correct! JanitorUtilities adds a few helper functions to your Janitors for syntactic sugar and convenience."
