[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.32.4"
lunar = "corecii/lunar@0.1.0"
lune = "lune-org/lune@0.8.8"
rojo = "rojo-rbx/rojo@7.4.4"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
selene = "kampfkarren/selene@0.27.1"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
